version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sonicbridge-frontend:latest
    container_name: sonicbridge-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
